# Model arguments
model_name_or_path: /mnt/data-rundong/VLA-experiments/TATS-tokenized/Mistral-7B-zero3/checkpoint-25000/
model_revision: main
torch_dtype: float16
use_flash_attention_2: false

# Data training arguments
preprocessing_num_workers: 12
data_root: /mnt/data-rundong/bridge2_processed/tokenized/
padding_side: left
num_visual_action_tokens: 16384
static_video_description:
  - ""
dataset_type: dataset # or iterable_dataset
